name: Terraform

on:
  push:
    branches:
      - vasil  # Set this to your main branch name
  pull_request:
    branches:
      - vasil  # Set this to include your main branch for PRs

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-north-1'  # Your AWS region
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 'latest'  # Specify your Terraform version here

    - name: Setup Terraform Cloud Credentials
      run: echo "credentials \"app.terraform.io\" { token = \"${{ secrets.TF_API_TOKEN }}\" }" > ~/.terraformrc    

    - name: Terraform Init
      run: terraform init
      working-directory: ./infrastructure

    - name: Terraform Apply Destroy
      run: terraform apply -destroy
      working-directory: ./infrastructure